FROM postgres:15

WORKDIR /scripts
COPY .pgpass /root/.pgpass
COPY *.sh .

RUN chmod 600 /root/.pgpass && \
    chmod +x *.sh

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

CMD ["./setup.sh"]